version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:54321/

  postgres:
    image: postgres:latest
    container_name: postgre
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: